<?php

namespace Database\Seeders;

use App\Models\District;
use Illuminate\Database\Seeder;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['department_id' => 1, 'name' => 'DISTRITO SIN ESPECIFICAR'],
            ['department_id' => 1, 'name' => 'LORETO'],
            ['department_id' => 1, 'name' => 'SAN CARLOS'],
            ['department_id' => 1, 'name' => 'SAN LAZARO'],
            ['department_id' => 1, 'name' => 'YBY YAU'],
            ['department_id' => 1, 'name' => 'AZOTEY'],
            ['department_id' => 1, 'name' => 'SARGENTO JOSE F. LOPEZ(EX-PUENTESIÑO)'],
            ['department_id' => 1, 'name' => 'PASO BARRETO'],
            ['department_id' => 1, 'name' => 'SAN ALFREDO'],
            ['department_id' => 1, 'name' => 'ARROYITO'],
            ['department_id' => 1, 'name' => 'CONCEPCION'],
            ['department_id' => 1, 'name' => 'BELEN'],
            ['department_id' => 1, 'name' => 'HORQUETA'],

            ['department_id' => 2, 'name' => 'DISTRITO SIN ESPECIFICAR'],
            ['department_id' => 2, 'name' => 'TACUATI'],
            ['department_id' => 2, 'name' => 'UNION'],
            ['department_id' => 2, 'name' => '25 DE DICIEMBRE'],
            ['department_id' => 2, 'name' => 'VILLA DEL ROSARIO'],
            ['department_id' => 2, 'name' => 'GRAL RESQUIN'],
            ['department_id' => 2, 'name' => 'YATAITY DEL NORTE'],
            ['department_id' => 2, 'name' => 'GUAYAIBI'],
            ['department_id' => 2, 'name' => 'SANTA ROSA AGUARAY'],
            ['department_id' => 2, 'name' => 'CAPIIBARY'],
            ['department_id' => 2, 'name' => 'LIBERACION'],
            ['department_id' => 2, 'name' => 'YRYBUCUA'],
            ['department_id' => 2, 'name' => 'SAN PEDRO YCUAMANDYJU'],
            ['department_id' => 2, 'name' => 'ANTEQUERA'],
            ['department_id' => 2, 'name' => 'CHORE'],
            ['department_id' => 2, 'name' => 'GRAL AQUINO'],
            ['department_id' => 2, 'name' => 'ITACURUBI DEL ROSARIO'],
            ['department_id' => 2, 'name' => 'LIMA'],
            ['department_id' => 2, 'name' => 'NUEVA GERMANIA'],
            ['department_id' => 2, 'name' => 'SAN ESTANISLAO'],
            ['department_id' => 2, 'name' => 'SAN PABLO'],

            ['department_id' => 3, 'name' => 'DISTRITO SIN ESPECIFICAR'],
            ['department_id' => 3, 'name' => 'CARAGUATAY'],
            ['department_id' => 3, 'name' => 'CAACUPE'],
            ['department_id' => 3, 'name' => 'ALTOS'],
            ['department_id' => 3, 'name' => 'ARROYOS Y ESTEROS'],
            ['department_id' => 3, 'name' => 'ATYRA'],
            ['department_id' => 3, 'name' => 'EMBOSCADA'],
            ['department_id' => 3, 'name' => 'EUSEBIO AYALA'],
            ['department_id' => 3, 'name' => 'ISLA PUCU'],
            ['department_id' => 3, 'name' => 'ITACURUBI DE LA CORDILLERA'],
            ['department_id' => 3, 'name' => 'JUAN DE MENA'],
            ['department_id' => 3, 'name' => 'LOMA GRANDE'],
            ['department_id' => 3, 'name' => 'MBOKAYATY DEL YHAGUY'],
            ['department_id' => 3, 'name' => 'NUEVA COLOMBIA'],
            ['department_id' => 3, 'name' => 'PIRIBEBUY'],
            ['department_id' => 3, 'name' => 'PRIMERO DE MARZO'],
            ['department_id' => 3, 'name' => 'SAN BERNARDINO'],
            ['department_id' => 3, 'name' => 'SANTA ELENA'],
            ['department_id' => 3, 'name' => 'TOBATI'],
            ['department_id' => 3, 'name' => 'VALENZUELA'],
            ['department_id' => 3, 'name' => 'SAN JOSE OBRERO'],

            ['department_id' => 4, 'name' => 'DISTRITO SIN ESPECIFICAR'],
            ['department_id' => 4, 'name' => 'PASO YOBAI'],
            ['department_id' => 4, 'name' => 'TROCHE'],
            ['department_id' => 4, 'name' => 'TEBICUARY'],
            ['department_id' => 4, 'name' => 'VILLARRICA'],
            ['department_id' => 4, 'name' => 'BORJA'],
            ['department_id' => 4, 'name' => 'MAURICIO JOSE TROCHE'],
            ['department_id' => 4, 'name' => 'CNEL. MARTINEZ'],
            ['department_id' => 4, 'name' => 'FELIX PEREZ CARDOZO'],
            ['department_id' => 4, 'name' => 'GRAL GARAY'],
            ['department_id' => 4, 'name' => 'COLONIA INDEPENDENCIA'],
            ['department_id' => 4, 'name' => 'ITAPE'],
            ['department_id' => 4, 'name' => 'ITURBE'],
            ['department_id' => 4, 'name' => 'JOSE FASSARDI'],
            ['department_id' => 4, 'name' => 'MBOCAYATY'],
            ['department_id' => 4, 'name' => 'NATALICIO TALAVERA'],
            ['department_id' => 4, 'name' => 'ÑUMI'],
            ['department_id' => 4, 'name' => 'SAN SALVADOR'],
            ['department_id' => 4, 'name' => 'YATAITY'],
            ['department_id' => 4, 'name' => 'DR BOTTRELL'],

            ['department_id' => 5, 'name' => 'DISTRITO SIN ESPECIFICAR'],
            ['department_id' => 5, 'name' => 'MCAL LOPEZ'],
            ['department_id' => 5, 'name' => 'REPATRIACIÓN'],
            ['department_id' => 5, 'name' => 'SANTA ROSA MBUTUY'],
            ['department_id' => 5, 'name' => 'J EULOGIO ESTIGARRIBIA'],
            ['department_id' => 5, 'name' => 'JOSE D OCAMPOS'],
            ['department_id' => 5, 'name' => 'RI3 CORRALES'],
            ['department_id' => 5, 'name' => 'RAUL A OVIEDO'],
            ['department_id' => 5, 'name' => '3 DE FEBRERO'],
            ['department_id' => 5, 'name' => 'SIMON BOLIVAR'],
            ['department_id' => 5, 'name' => 'LA PASTORA'],
            ['department_id' => 5, 'name' => 'VAQUERIA'],
            ['department_id' => 5, 'name' => 'TEMBIAPORA'],
            ['department_id' => 5, 'name' => 'NUEVA TOLEDO'],
            ['department_id' => 5, 'name' => 'CORONEL OVIEDO'],
            ['department_id' => 5, 'name' => 'CAAGUAZU'],
            ['department_id' => 5, 'name' => 'CARAYAO'],
            ['department_id' => 5, 'name' => 'CECILIO BAEZ'],
            ['department_id' => 5, 'name' => 'NUEVA LONDRES'],
            ['department_id' => 5, 'name' => 'SAN JOAQUIN'],
            ['department_id' => 5, 'name' => 'SAN JOSE DE LOS ARROYOS'],
            ['department_id' => 5, 'name' => 'YHU'],
            ['department_id' => 5, 'name' => 'DR. JUAN MANUEL FRUTOS'],

            ['department_id' => 6, 'name' => 'DISTRITO SIN ESPECIFICAR'],
            ['department_id' => 6, 'name' => 'YUTY'],
            ['department_id' => 6, 'name' => 'YEGROS'],
            ['department_id' => 6, 'name' => 'ABAI'],
            ['department_id' => 6, 'name' => 'BUENA VISTA'],
            ['department_id' => 6, 'name' => '3 DE MAYO'],
            ['department_id' => 6, 'name' => 'TAVAI'],
            ['department_id' => 6, 'name' => 'DR MOISES BERTONI'],
            ['department_id' => 6, 'name' => 'GRAL HIGINIO MORINIGO'],
            ['department_id' => 6, 'name' => 'SAN JUAN NEPOMUCENO'],
            ['department_id' => 6, 'name' => 'MACIEL'],
            ['department_id' => 6, 'name' => 'TUPA RENDA'],
            ['department_id' => 6, 'name' => 'CAAZAPA'],

            ['department_id' => 7, 'name' => 'DISTRITO SIN ESPECIFICAR'],
            ['department_id' => 7, 'name' => 'SAN JUAN PARANA'],
            ['department_id' => 7, 'name' => 'ENCARNACION'],
            ['department_id' => 7, 'name' => 'BELLA VISTA SUR'],
            ['department_id' => 7, 'name' => 'CAMBYRETA'],
            ['department_id' => 7, 'name' => 'CAPITAN MEZA'],
            ['department_id' => 7, 'name' => 'CARMEN DEL PARANA'],
            ['department_id' => 7, 'name' => 'CAPITAN MIRANDA'],
            ['department_id' => 7, 'name' => 'CORONEL BOGADO'],
            ['department_id' => 7, 'name' => 'FRAM'],
            ['department_id' => 7, 'name' => 'GENERAL ARTIGAS'],
            ['department_id' => 7, 'name' => 'GRAL DELGADO'],
            ['department_id' => 7, 'name' => 'HOHENAU'],
            ['department_id' => 7, 'name' => 'JESUS'],
            ['department_id' => 7, 'name' => 'OBLIGADO'],
            ['department_id' => 7, 'name' => 'SAN COSME Y DAMIAN'],
            ['department_id' => 7, 'name' => 'SAN PEDRO PARANA'],
            ['department_id' => 7, 'name' => 'NUEVA ALBORADA'],
            ['department_id' => 7, 'name' => 'TRINIDAD'],
            ['department_id' => 7, 'name' => 'NATALIO'],
            ['department_id' => 7, 'name' => 'LEANDRO OVIEDO'],
            ['department_id' => 7, 'name' => 'SAN RAFAEL PARANA'],
            ['department_id' => 7, 'name' => 'CARLOS A LOPEZ'],
            ['department_id' => 7, 'name' => 'MAYOR OTAÑO'],
            ['department_id' => 7, 'name' => 'EDELIRA'],
            ['department_id' => 7, 'name' => 'LA PAZ'],
            ['department_id' => 7, 'name' => 'TOMAS R. PEREIRA'],
            ['department_id' => 7, 'name' => 'YATYTAY'],
            ['department_id' => 7, 'name' => 'ALTO VERA'],
            ['department_id' => 7, 'name' => 'PIRAPO'],
            ['department_id' => 7, 'name' => 'ITAPUA POTY'],
            ['department_id' => 7, 'name' => 'SAN ANTONIO MI'],

            ['department_id' => 8, 'name' => 'DISTRITO SIN ESPECIFICAR'],
            ['department_id' => 8, 'name' => 'VILLA FLORIDA'],
            ['department_id' => 8, 'name' => 'YABEBYRY'],
            ['department_id' => 8, 'name' => 'SAN JUAN BAUTISTA'],
            ['department_id' => 8, 'name' => 'AYOLAS'],
            ['department_id' => 8, 'name' => 'SAN IGNACIO'],
            ['department_id' => 8, 'name' => 'SAN MIGUEL'],
            ['department_id' => 8, 'name' => 'SAN PATRICIO'],
            ['department_id' => 8, 'name' => 'SANTA MARIA'],
            ['department_id' => 8, 'name' => 'SANTA ROSA'],
            ['department_id' => 8, 'name' => 'SANTIAGO'],

            ['department_id' => 9, 'name' => 'DISTRITO SIN ESPECIFICAR'],
            ['department_id' => 9, 'name' => 'ESCOBAR'],
            ['department_id' => 9, 'name' => 'MARIA ANTONIA'],
            ['department_id' => 9, 'name' => 'PARAGUARI'],
            ['department_id' => 9, 'name' => 'ACAHAY'],
            ['department_id' => 9, 'name' => 'CAAPUCU'],
            ['department_id' => 9, 'name' => 'CABALLERO'],
            ['department_id' => 9, 'name' => 'CARAPEGUA'],
            ['department_id' => 9, 'name' => 'LA COLMENA'],
            ['department_id' => 9, 'name' => 'MBUYAPEY'],
            ['department_id' => 9, 'name' => 'PIRAYU'],
            ['department_id' => 9, 'name' => 'QUIINDY'],
            ['department_id' => 9, 'name' => 'ROQUE GONZALEZ'],
            ['department_id' => 9, 'name' => 'SAPUCAI'],
            ['department_id' => 9, 'name' => 'YBYCUI'],
            ['department_id' => 9, 'name' => 'QUYQUYHO'],
            ['department_id' => 9, 'name' => 'YBYTIMI'],
            ['department_id' => 9, 'name' => 'TEBICUARYMI'],
            ['department_id' => 9, 'name' => 'YAGUARON'],

            ['department_id' => 10,	'name' => 'DISTRITO SIN ESPECIFICAR'],
            ['department_id' => 10,	'name' => 'SANTA FE DEL PARANA'],
            ['department_id' => 10,	'name' => 'TAVAPY'],
            ['department_id' => 10,	'name' => 'HERNANDARIAS'],
            ['department_id' => 10,	'name' => 'DOMINGO M IRALA'],
            ['department_id' => 10,	'name' => 'ÑACUNDAY'],
            ['department_id' => 10,	'name' => 'CIUDAD DEL ESTE'],
            ['department_id' => 10,	'name' => 'J L MALLORQUIN'],
            ['department_id' => 10,	'name' => 'ITAKYRY'],
            ['department_id' => 10,	'name' => 'JUAN E OLEARY'],
            ['department_id' => 10,	'name' => 'PTE FRANCO'],
            ['department_id' => 10,	'name' => 'YGUAZU'],
            ['department_id' => 10,	'name' => 'SAN CRISTOBAL'],
            ['department_id' => 10,	'name' => 'ITAIPYTE'],
            ['department_id' => 10,	'name' => 'SANTA RITA'],
            ['department_id' => 10,	'name' => 'CEDRALES'],
            ['department_id' => 10,	'name' => 'MINGA GUAZU'],
            ['department_id' => 10,	'name' => 'SAN ALBERTO'],
            ['department_id' => 10,	'name' => 'MINGA PORA'],
            ['department_id' => 10,	'name' => 'MBARACAYU'],
            ['department_id' => 10,	'name' => 'NARANJAL'],
            ['department_id' => 10,	'name' => 'IRUÑA'],
            ['department_id' => 10,	'name' => 'SANTA ROSA MONDAY'],

            ['department_id' => 11,	'name' => 'DISTRITO SIN ESPECIFICAR'],
            ['department_id' => 11,	'name' => 'ÑEMBY'],
            ['department_id' => 11,	'name' => 'AREGUA'],
            ['department_id' => 11,	'name' => 'CAPIATA'],
            ['department_id' => 11,	'name' => 'FERNADO DE LA MORA'],
            ['department_id' => 11,	'name' => 'GUARAMBARE'],
            ['department_id' => 11,	'name' => 'ITA'],
            ['department_id' => 11,	'name' => 'ITAUGUA'],
            ['department_id' => 11,	'name' => 'LAMBARE'],
            ['department_id' => 11,	'name' => 'LIMPIO'],
            ['department_id' => 11,	'name' => 'LUQUE'],
            ['department_id' => 11,	'name' => 'ROQUE ALONSO'],
            ['department_id' => 11,	'name' => 'NUEVA ITALIA'],
            ['department_id' => 11,	'name' => 'SAN ANTONIO'],
            ['department_id' => 11,	'name' => 'SAN LORENZO'],
            ['department_id' => 11,	'name' => 'VILLA ELISA'],
            ['department_id' => 11,	'name' => 'VILLETA'],
            ['department_id' => 11,	'name' => 'YPACARAI'],
            ['department_id' => 11,	'name' => 'YPANE'],
            ['department_id' => 11,	'name' => 'J SALDIVAR'],

            ['department_id' => 12,	'name' => 'DISTRITO SIN ESPECIFICAR'],
            ['department_id' => 12,	'name' => 'VILLALBIN'],
            ['department_id' => 12,	'name' => 'PILAR'],
            ['department_id' => 12,	'name' => 'ALBERDI'],
            ['department_id' => 12,	'name' => 'CERRITO'],
            ['department_id' => 12,	'name' => 'DESMOCHADOS'],
            ['department_id' => 12,	'name' => 'GRAL DIAZ'],
            ['department_id' => 12,	'name' => 'GUAZU CUA'],
            ['department_id' => 12,	'name' => 'HUMAITA'],
            ['department_id' => 12,	'name' => 'ISLA UMBU'],
            ['department_id' => 12,	'name' => 'LAURELES'],
            ['department_id' => 12,	'name' => 'MAYOR MARTINEZ'],
            ['department_id' => 12,	'name' => 'PASO DE PATRIA'],
            ['department_id' => 12,	'name' => 'SAN JUAN ÑEEMBUCU'],
            ['department_id' => 12,	'name' => 'TACUARAS'],
            ['department_id' => 12,	'name' => 'VILLA FRANCA'],
            ['department_id' => 12,	'name' => 'VILLA OLIVA'],

            ['department_id' => 13,	'name' => 'DISTRITO SIN ESPECIFICAR'],
            ['department_id' => 13,	'name' => 'ZANJA PYTA'],
            ['department_id' => 13,	'name' => 'PEDRO JUAN CABALLERO'],
            ['department_id' => 13,	'name' => 'BELLA VISTA NORTE'],
            ['department_id' => 13,	'name' => 'CAPITAN BADO'],
            ['department_id' => 13,	'name' => 'KARAPA I'],

            ['department_id' => 14,	'name' => 'DISTRITO SIN ESPECIFICAR'],
            ['department_id' => 14,	'name' => 'NUEVA ESPERANZA'],
            ['department_id' => 14,	'name' => 'SALTOS DEL GUAIRA'],
            ['department_id' => 14,	'name' => 'CURUGUATY'],
            ['department_id' => 14,	'name' => 'YGATIMI'],
            ['department_id' => 14,	'name' => 'MARACANA'],
            ['department_id' => 14,	'name' => 'YBYRAROBANA'],
            ['department_id' => 14,	'name' => 'YPEJHU'],
            ['department_id' => 14,	'name' => 'CORPUS CRISTHI'],
            ['department_id' => 14,	'name' => 'ITANARA'],
            ['department_id' => 14,	'name' => 'CABALLERO ALVAREZ'],
            ['department_id' => 14,	'name' => 'KATUETE'],
            ['department_id' => 14,	'name' => 'LA PALOMA'],
            ['department_id' => 14,	'name' => 'YASY KAÑY'],
            ['department_id' => 14,	'name' => 'YBYRAROVANA'],
            ['department_id' => 14,	'name' => 'YBYPYTA'],

            ['department_id' => 15,	'name' => 'DISTRITO SIN ESPECIFICAR'],
            ['department_id' => 15,	'name' => 'IRALA FERNANDEZ'],
            ['department_id' => 15,	'name' => 'GRAL. BRUGUEZ'],
            ['department_id' => 15,	'name' => 'BENJAMIN ACEVAL'],
            ['department_id' => 15,	'name' => 'PINASCO'],
            ['department_id' => 15,	'name' => 'TTE. ESTEBAN MARTINEZ'],
            ['department_id' => 15,	'name' => 'VILLA HAYES'],
            ['department_id' => 15,	'name' => 'JOSE FALCON'],
            ['department_id' => 15,	'name' => 'NANAWA'],

            ['department_id' => 16,	'name' => 'DISTRITO SIN ESPECIFICAR'],
            ['department_id' => 16,	'name' => 'BAHIA NEGRA'],
            ['department_id' => 16,	'name' => 'FUERTE OLIMPO'],
            ['department_id' => 16,	'name' => 'LA VICTORIA'],
            ['department_id' => 16,	'name' => 'PTO.CASADO - LA VICTORIA'],

            ['department_id' => 17,	'name' => 'DISTRITO SIN ESPECIFICAR'],
            ['department_id' => 17,	'name' => 'FILADELFIA'],
            ['department_id' => 17,	'name' => 'MCAL  ESTIGARRIBIA'],
            ['department_id' => 17,	'name' => 'PEDRO P. PEÑA'],
            ['department_id' => 17,	'name' => 'GRAL.EUGENIO A. GARAY'],
            ['department_id' => 17,	'name' => 'LOMA PLATA'],
        ];
        District::insert($data);
    }
}
